default:
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "kingdom_rush_user"
    password: ${env:DB_PASSWORD}
    database: "kingdom_rush_db"
    entities: ["dist/models/*.js"]
    logging: false
    synchronize: false
    dropSchema: false
    migrations: ["dist/migrations/*.js"]
    cli:
        migrationsDir: "src/migrations"

test:
    type: "postgres"
    host: "localhost"
    port: 5432
    username: "kingdom_rush_user"
    password: ${env:DB_PASSWORD}
    database: "test_db"
    entities: ["src/models/*.ts"]
    logging: false
    synchronize: true
    dropSchema: true
